### ISSUE TITLE
Check bulk ip's

### ISSUE THREAD

**Issue by R0GGER** [splitice/bulkdnsblcheck#1]
Is it possible to check a list of 200 ip's in text format?
example: ./rbl.sh details /path/listed-ips.txt

**Comment by splitice** [comment]
Not currently, but feel free to submit a pull request or patch for the functionality - its not a bad idea.

it would probably be better to interface it like:

```
./rbl.sh details file /path/listed-ips.txt
```

This way any ambiguity between IP addresses and files can be avoided.
